// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/database/network_credentials.dart';
import 'models/objectbox/album.dart';
import 'models/objectbox/album_config.dart';
import 'models/objectbox/album_file.dart';
import 'models/objectbox/file_tag.dart';
import 'models/objectbox/user_preference.dart';
import 'models/objectbox/video_library.dart';
import 'models/objectbox/video_library_config.dart';
import 'models/objectbox/video_library_file.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5143898110390256028),
    name: 'Album',
    lastPropertyId: const obx_int.IdUid(8, 7104370144707587186),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1929943447747413047),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8242535741771196657),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 7388045328485041676),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7971044673736803455),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3951312716219981008),
        name: 'coverImagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1087904695384721368),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5556788609067141943),
        name: 'modifiedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2780012000551111728),
        name: 'colorTheme',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7104370144707587186),
        name: 'isSystemAlbum',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 9129152327337653024),
    name: 'AlbumFile',
    lastPropertyId: const obx_int.IdUid(7, 1933986167312715564),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8445380510269387539),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4794139252072615300),
        name: 'albumId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 8910574062951500387),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3626758200920050589),
        name: 'filePath',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 2910510691877524821),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6119208815174450843),
        name: 'orderIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3972177555062226749),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2991473314200879026),
        name: 'caption',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1933986167312715564),
        name: 'isCover',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8336324679431031106),
    name: 'FileTag',
    lastPropertyId: const obx_int.IdUid(3, 1165792884101459074),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5113321196187212683),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8183118758118872870),
        name: 'filePath',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 5461401798872689695),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1165792884101459074),
        name: 'tag',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 7936667415471607556),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5943290169100748402),
    name: 'NetworkCredentials',
    lastPropertyId: const obx_int.IdUid(9, 5874694679331112670),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7895101648917096223),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6339263640462601610),
        name: 'serviceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1690596764556311930),
        name: 'host',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8479007645482200673),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7168465125157893157),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6928731021884167758),
        name: 'port',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7922582909552015213),
        name: 'domain',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7400665885988518880),
        name: 'additionalOptions',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5874694679331112670),
        name: 'lastConnected',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1325907199832929183),
    name: 'UserPreference',
    lastPropertyId: const obx_int.IdUid(8, 2141535480574122672),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 656663352622602341),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8639318240102994986),
        name: 'key',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 1453680630834694226),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2125129317340269927),
        name: 'stringValue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3961414552172590357),
        name: 'intValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7123151727405562764),
        name: 'doubleValue',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5206864587505014452),
        name: 'boolValue',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2517845582945166902),
        name: 'typeValue',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2141535480574122672),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 8093577245119292471),
    name: 'AlbumConfig',
    lastPropertyId: const obx_int.IdUid(16, 7195634996299692075),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5205840095978072328),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 277614084488294581),
        name: 'albumId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(7, 8272886834281330939),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7382013429497652143),
        name: 'includeSubdirectories',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2811044461506168831),
        name: 'fileExtensions',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6963933363374269828),
        name: 'autoRefresh',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4228363794854707608),
        name: 'maxFileCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3704849086469515431),
        name: 'sortBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8958123274497082350),
        name: 'sortAscending',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4485916255625962833),
        name: 'excludePatterns',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5478363898327082683),
        name: 'enableAutoRules',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7198277050346662436),
        name: 'directories',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5498721553129892912),
        name: 'lastScanTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3911821814749156053),
        name: 'fileCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6413934631075641102),
        name: 'fileExtensionsList',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4576915792095916095),
        name: 'excludePatternsList',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7195634996299692075),
        name: 'directoriesList',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 1221758574361293866),
    name: 'VideoLibrary',
    lastPropertyId: const obx_int.IdUid(8, 4150308620522179873),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5584380311508327753),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7074027490295188885),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 1356818697637944965),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1854028471052069891),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3855235098721891924),
        name: 'coverImagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2054462555020246138),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4067516748570721321),
        name: 'modifiedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6536621792474958007),
        name: 'colorTheme',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4150308620522179873),
        name: 'isSystemLibrary',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 5839977632250564203),
    name: 'VideoLibraryConfig',
    lastPropertyId: const obx_int.IdUid(16, 567327745562898334),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6174414858218042375),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 915473089431133066),
        name: 'videoLibraryId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(9, 1976672364964737810),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5957568411830936336),
        name: 'includeSubdirectories',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8689645382577592670),
        name: 'fileExtensions',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4375848151248213422),
        name: 'autoRefresh',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 564004514557567819),
        name: 'maxFileCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3223141345054565399),
        name: 'sortBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8870670427647753203),
        name: 'sortAscending',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6856377625356011510),
        name: 'excludePatterns',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7400570477919294979),
        name: 'enableAutoRules',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 9118617357795126334),
        name: 'directories',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1396750611570234461),
        name: 'lastScanTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5847118959332538714),
        name: 'fileCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4485512187051438041),
        name: 'fileExtensionsList',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 295225553395887163),
        name: 'excludePatternsList',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 567327745562898334),
        name: 'directoriesList',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 1050307742319782002),
    name: 'VideoLibraryFile',
    lastPropertyId: const obx_int.IdUid(6, 693465544661155762),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4735548239728623352),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8336295703818267215),
        name: 'videoLibraryId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(10, 477406062999369568),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9220028997854741047),
        name: 'filePath',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(11, 6189961830114533234),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2278951804529003072),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3845029734220531780),
        name: 'caption',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 693465544661155762),
        name: 'orderIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(9, 1050307742319782002),
    lastIndexId: const obx_int.IdUid(11, 6189961830114533234),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Album: obx_int.EntityDefinition<Album>(
      model: _entities[0],
      toOneRelations: (Album object) => [],
      toManyRelations: (Album object) => {},
      getId: (Album object) => object.id,
      setId: (Album object, int id) {
        object.id = id;
      },
      objectToFB: (Album object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final coverImagePathOffset = object.coverImagePath == null
            ? null
            : fbb.writeString(object.coverImagePath!);
        final colorThemeOffset = object.colorTheme == null
            ? null
            : fbb.writeString(object.colorTheme!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, coverImagePathOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.modifiedAt.millisecondsSinceEpoch);
        fbb.addOffset(6, colorThemeOffset);
        fbb.addBool(7, object.isSystemAlbum);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final coverImagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final modifiedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final colorThemeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final isSystemAlbumParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = Album(
          name: nameParam,
          description: descriptionParam,
          coverImagePath: coverImagePathParam,
          createdAt: createdAtParam,
          modifiedAt: modifiedAtParam,
          colorTheme: colorThemeParam,
          isSystemAlbum: isSystemAlbumParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    AlbumFile: obx_int.EntityDefinition<AlbumFile>(
      model: _entities[1],
      toOneRelations: (AlbumFile object) => [],
      toManyRelations: (AlbumFile object) => {},
      getId: (AlbumFile object) => object.id,
      setId: (AlbumFile object, int id) {
        object.id = id;
      },
      objectToFB: (AlbumFile object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final captionOffset = object.caption == null
            ? null
            : fbb.writeString(object.caption!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.albumId);
        fbb.addOffset(2, filePathOffset);
        fbb.addInt64(3, object.orderIndex);
        fbb.addInt64(4, object.addedAt.millisecondsSinceEpoch);
        fbb.addOffset(5, captionOffset);
        fbb.addBool(6, object.isCover);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final albumIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final orderIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final captionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final isCoverParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = AlbumFile(
          albumId: albumIdParam,
          filePath: filePathParam,
          orderIndex: orderIndexParam,
          addedAt: addedAtParam,
          caption: captionParam,
          isCover: isCoverParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    FileTag: obx_int.EntityDefinition<FileTag>(
      model: _entities[2],
      toOneRelations: (FileTag object) => [],
      toManyRelations: (FileTag object) => {},
      getId: (FileTag object) => object.id,
      setId: (FileTag object, int id) {
        object.id = id;
      },
      objectToFB: (FileTag object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final tagOffset = fbb.writeString(object.tag);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, filePathOffset);
        fbb.addOffset(2, tagOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final tagParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = FileTag(filePath: filePathParam, tag: tagParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    NetworkCredentials: obx_int.EntityDefinition<NetworkCredentials>(
      model: _entities[3],
      toOneRelations: (NetworkCredentials object) => [],
      toManyRelations: (NetworkCredentials object) => {},
      getId: (NetworkCredentials object) => object.id,
      setId: (NetworkCredentials object, int id) {
        object.id = id;
      },
      objectToFB: (NetworkCredentials object, fb.Builder fbb) {
        final serviceTypeOffset = fbb.writeString(object.serviceType);
        final hostOffset = fbb.writeString(object.host);
        final usernameOffset = fbb.writeString(object.username);
        final passwordOffset = fbb.writeString(object.password);
        final domainOffset = object.domain == null
            ? null
            : fbb.writeString(object.domain!);
        final additionalOptionsOffset = object.additionalOptions == null
            ? null
            : fbb.writeString(object.additionalOptions!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, serviceTypeOffset);
        fbb.addOffset(2, hostOffset);
        fbb.addOffset(3, usernameOffset);
        fbb.addOffset(4, passwordOffset);
        fbb.addInt64(5, object.port);
        fbb.addOffset(6, domainOffset);
        fbb.addOffset(7, additionalOptionsOffset);
        fbb.addInt64(8, object.lastConnected.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final serviceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final hostParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final passwordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final portParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final domainParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final additionalOptionsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final lastConnectedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = NetworkCredentials(
          serviceType: serviceTypeParam,
          host: hostParam,
          username: usernameParam,
          password: passwordParam,
          port: portParam,
          domain: domainParam,
          additionalOptions: additionalOptionsParam,
          lastConnected: lastConnectedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    UserPreference: obx_int.EntityDefinition<UserPreference>(
      model: _entities[4],
      toOneRelations: (UserPreference object) => [],
      toManyRelations: (UserPreference object) => {},
      getId: (UserPreference object) => object.id,
      setId: (UserPreference object, int id) {
        object.id = id;
      },
      objectToFB: (UserPreference object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final stringValueOffset = object.stringValue == null
            ? null
            : fbb.writeString(object.stringValue!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, stringValueOffset);
        fbb.addInt64(3, object.intValue);
        fbb.addFloat64(4, object.doubleValue);
        fbb.addBool(5, object.boolValue);
        fbb.addInt32(6, object.typeValue);
        fbb.addInt64(7, object.timestamp);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final stringValueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final intValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final doubleValueParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final boolValueParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final typeValueParam = const fb.Int32Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = UserPreference(
          id: idParam,
          key: keyParam,
          stringValue: stringValueParam,
          intValue: intValueParam,
          doubleValue: doubleValueParam,
          boolValue: boolValueParam,
          typeValue: typeValueParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
    AlbumConfig: obx_int.EntityDefinition<AlbumConfig>(
      model: _entities[5],
      toOneRelations: (AlbumConfig object) => [],
      toManyRelations: (AlbumConfig object) => {},
      getId: (AlbumConfig object) => object.id,
      setId: (AlbumConfig object, int id) {
        object.id = id;
      },
      objectToFB: (AlbumConfig object, fb.Builder fbb) {
        final fileExtensionsOffset = fbb.writeString(object.fileExtensions);
        final sortByOffset = fbb.writeString(object.sortBy);
        final excludePatternsOffset = fbb.writeString(object.excludePatterns);
        final directoriesOffset = fbb.writeString(object.directories);
        final fileExtensionsListOffset = fbb.writeList(
          object.fileExtensionsList
              .map(fbb.writeString)
              .toList(growable: false),
        );
        final excludePatternsListOffset = fbb.writeList(
          object.excludePatternsList
              .map(fbb.writeString)
              .toList(growable: false),
        );
        final directoriesListOffset = fbb.writeList(
          object.directoriesList.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.albumId);
        fbb.addBool(2, object.includeSubdirectories);
        fbb.addOffset(3, fileExtensionsOffset);
        fbb.addBool(4, object.autoRefresh);
        fbb.addInt64(5, object.maxFileCount);
        fbb.addOffset(6, sortByOffset);
        fbb.addBool(7, object.sortAscending);
        fbb.addOffset(8, excludePatternsOffset);
        fbb.addBool(9, object.enableAutoRules);
        fbb.addOffset(10, directoriesOffset);
        fbb.addInt64(11, object.lastScanTime?.millisecondsSinceEpoch);
        fbb.addInt64(12, object.fileCount);
        fbb.addOffset(13, fileExtensionsListOffset);
        fbb.addOffset(14, excludePatternsListOffset);
        fbb.addOffset(15, directoriesListOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastScanTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final albumIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final includeSubdirectoriesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final fileExtensionsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final autoRefreshParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final maxFileCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final sortByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final sortAscendingParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final excludePatternsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final enableAutoRulesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final directoriesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final lastScanTimeParam = lastScanTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastScanTimeValue);
        final fileCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final object =
            AlbumConfig(
                albumId: albumIdParam,
                includeSubdirectories: includeSubdirectoriesParam,
                fileExtensions: fileExtensionsParam,
                autoRefresh: autoRefreshParam,
                maxFileCount: maxFileCountParam,
                sortBy: sortByParam,
                sortAscending: sortAscendingParam,
                excludePatterns: excludePatternsParam,
                enableAutoRules: enableAutoRulesParam,
                directories: directoriesParam,
                lastScanTime: lastScanTimeParam,
                fileCount: fileCountParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..fileExtensionsList = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 30, [])
              ..excludePatternsList = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 32, [])
              ..directoriesList = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 34, []);

        return object;
      },
    ),
    VideoLibrary: obx_int.EntityDefinition<VideoLibrary>(
      model: _entities[6],
      toOneRelations: (VideoLibrary object) => [],
      toManyRelations: (VideoLibrary object) => {},
      getId: (VideoLibrary object) => object.id,
      setId: (VideoLibrary object, int id) {
        object.id = id;
      },
      objectToFB: (VideoLibrary object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final coverImagePathOffset = object.coverImagePath == null
            ? null
            : fbb.writeString(object.coverImagePath!);
        final colorThemeOffset = object.colorTheme == null
            ? null
            : fbb.writeString(object.colorTheme!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, coverImagePathOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.modifiedAt.millisecondsSinceEpoch);
        fbb.addOffset(6, colorThemeOffset);
        fbb.addBool(7, object.isSystemLibrary);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final coverImagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final modifiedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final colorThemeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final isSystemLibraryParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = VideoLibrary(
          name: nameParam,
          description: descriptionParam,
          coverImagePath: coverImagePathParam,
          createdAt: createdAtParam,
          modifiedAt: modifiedAtParam,
          colorTheme: colorThemeParam,
          isSystemLibrary: isSystemLibraryParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    VideoLibraryConfig: obx_int.EntityDefinition<VideoLibraryConfig>(
      model: _entities[7],
      toOneRelations: (VideoLibraryConfig object) => [],
      toManyRelations: (VideoLibraryConfig object) => {},
      getId: (VideoLibraryConfig object) => object.id,
      setId: (VideoLibraryConfig object, int id) {
        object.id = id;
      },
      objectToFB: (VideoLibraryConfig object, fb.Builder fbb) {
        final fileExtensionsOffset = fbb.writeString(object.fileExtensions);
        final sortByOffset = fbb.writeString(object.sortBy);
        final excludePatternsOffset = fbb.writeString(object.excludePatterns);
        final directoriesOffset = fbb.writeString(object.directories);
        final fileExtensionsListOffset = fbb.writeList(
          object.fileExtensionsList
              .map(fbb.writeString)
              .toList(growable: false),
        );
        final excludePatternsListOffset = fbb.writeList(
          object.excludePatternsList
              .map(fbb.writeString)
              .toList(growable: false),
        );
        final directoriesListOffset = fbb.writeList(
          object.directoriesList.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.videoLibraryId);
        fbb.addBool(2, object.includeSubdirectories);
        fbb.addOffset(3, fileExtensionsOffset);
        fbb.addBool(4, object.autoRefresh);
        fbb.addInt64(5, object.maxFileCount);
        fbb.addOffset(6, sortByOffset);
        fbb.addBool(7, object.sortAscending);
        fbb.addOffset(8, excludePatternsOffset);
        fbb.addBool(9, object.enableAutoRules);
        fbb.addOffset(10, directoriesOffset);
        fbb.addInt64(11, object.lastScanTime?.millisecondsSinceEpoch);
        fbb.addInt64(12, object.fileCount);
        fbb.addOffset(13, fileExtensionsListOffset);
        fbb.addOffset(14, excludePatternsListOffset);
        fbb.addOffset(15, directoriesListOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastScanTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final videoLibraryIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final includeSubdirectoriesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final fileExtensionsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final autoRefreshParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final maxFileCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final sortByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final sortAscendingParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final excludePatternsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final enableAutoRulesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final directoriesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final lastScanTimeParam = lastScanTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastScanTimeValue);
        final fileCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final object =
            VideoLibraryConfig(
                videoLibraryId: videoLibraryIdParam,
                includeSubdirectories: includeSubdirectoriesParam,
                fileExtensions: fileExtensionsParam,
                autoRefresh: autoRefreshParam,
                maxFileCount: maxFileCountParam,
                sortBy: sortByParam,
                sortAscending: sortAscendingParam,
                excludePatterns: excludePatternsParam,
                enableAutoRules: enableAutoRulesParam,
                directories: directoriesParam,
                lastScanTime: lastScanTimeParam,
                fileCount: fileCountParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..fileExtensionsList = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 30, [])
              ..excludePatternsList = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 32, [])
              ..directoriesList = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 34, []);

        return object;
      },
    ),
    VideoLibraryFile: obx_int.EntityDefinition<VideoLibraryFile>(
      model: _entities[8],
      toOneRelations: (VideoLibraryFile object) => [],
      toManyRelations: (VideoLibraryFile object) => {},
      getId: (VideoLibraryFile object) => object.id,
      setId: (VideoLibraryFile object, int id) {
        object.id = id;
      },
      objectToFB: (VideoLibraryFile object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final captionOffset = object.caption == null
            ? null
            : fbb.writeString(object.caption!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.videoLibraryId);
        fbb.addOffset(2, filePathOffset);
        fbb.addInt64(3, object.addedAt.millisecondsSinceEpoch);
        fbb.addOffset(4, captionOffset);
        fbb.addInt64(5, object.orderIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final videoLibraryIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final captionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final orderIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = VideoLibraryFile(
          videoLibraryId: videoLibraryIdParam,
          filePath: filePathParam,
          addedAt: addedAtParam,
          caption: captionParam,
          orderIndex: orderIndexParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Album] entity fields to define ObjectBox queries.
class Album_ {
  /// See [Album.id].
  static final id = obx.QueryIntegerProperty<Album>(_entities[0].properties[0]);

  /// See [Album.name].
  static final name = obx.QueryStringProperty<Album>(
    _entities[0].properties[1],
  );

  /// See [Album.description].
  static final description = obx.QueryStringProperty<Album>(
    _entities[0].properties[2],
  );

  /// See [Album.coverImagePath].
  static final coverImagePath = obx.QueryStringProperty<Album>(
    _entities[0].properties[3],
  );

  /// See [Album.createdAt].
  static final createdAt = obx.QueryDateProperty<Album>(
    _entities[0].properties[4],
  );

  /// See [Album.modifiedAt].
  static final modifiedAt = obx.QueryDateProperty<Album>(
    _entities[0].properties[5],
  );

  /// See [Album.colorTheme].
  static final colorTheme = obx.QueryStringProperty<Album>(
    _entities[0].properties[6],
  );

  /// See [Album.isSystemAlbum].
  static final isSystemAlbum = obx.QueryBooleanProperty<Album>(
    _entities[0].properties[7],
  );
}

/// [AlbumFile] entity fields to define ObjectBox queries.
class AlbumFile_ {
  /// See [AlbumFile.id].
  static final id = obx.QueryIntegerProperty<AlbumFile>(
    _entities[1].properties[0],
  );

  /// See [AlbumFile.albumId].
  static final albumId = obx.QueryIntegerProperty<AlbumFile>(
    _entities[1].properties[1],
  );

  /// See [AlbumFile.filePath].
  static final filePath = obx.QueryStringProperty<AlbumFile>(
    _entities[1].properties[2],
  );

  /// See [AlbumFile.orderIndex].
  static final orderIndex = obx.QueryIntegerProperty<AlbumFile>(
    _entities[1].properties[3],
  );

  /// See [AlbumFile.addedAt].
  static final addedAt = obx.QueryDateProperty<AlbumFile>(
    _entities[1].properties[4],
  );

  /// See [AlbumFile.caption].
  static final caption = obx.QueryStringProperty<AlbumFile>(
    _entities[1].properties[5],
  );

  /// See [AlbumFile.isCover].
  static final isCover = obx.QueryBooleanProperty<AlbumFile>(
    _entities[1].properties[6],
  );
}

/// [FileTag] entity fields to define ObjectBox queries.
class FileTag_ {
  /// See [FileTag.id].
  static final id = obx.QueryIntegerProperty<FileTag>(
    _entities[2].properties[0],
  );

  /// See [FileTag.filePath].
  static final filePath = obx.QueryStringProperty<FileTag>(
    _entities[2].properties[1],
  );

  /// See [FileTag.tag].
  static final tag = obx.QueryStringProperty<FileTag>(
    _entities[2].properties[2],
  );
}

/// [NetworkCredentials] entity fields to define ObjectBox queries.
class NetworkCredentials_ {
  /// See [NetworkCredentials.id].
  static final id = obx.QueryIntegerProperty<NetworkCredentials>(
    _entities[3].properties[0],
  );

  /// See [NetworkCredentials.serviceType].
  static final serviceType = obx.QueryStringProperty<NetworkCredentials>(
    _entities[3].properties[1],
  );

  /// See [NetworkCredentials.host].
  static final host = obx.QueryStringProperty<NetworkCredentials>(
    _entities[3].properties[2],
  );

  /// See [NetworkCredentials.username].
  static final username = obx.QueryStringProperty<NetworkCredentials>(
    _entities[3].properties[3],
  );

  /// See [NetworkCredentials.password].
  static final password = obx.QueryStringProperty<NetworkCredentials>(
    _entities[3].properties[4],
  );

  /// See [NetworkCredentials.port].
  static final port = obx.QueryIntegerProperty<NetworkCredentials>(
    _entities[3].properties[5],
  );

  /// See [NetworkCredentials.domain].
  static final domain = obx.QueryStringProperty<NetworkCredentials>(
    _entities[3].properties[6],
  );

  /// See [NetworkCredentials.additionalOptions].
  static final additionalOptions = obx.QueryStringProperty<NetworkCredentials>(
    _entities[3].properties[7],
  );

  /// See [NetworkCredentials.lastConnected].
  static final lastConnected = obx.QueryDateProperty<NetworkCredentials>(
    _entities[3].properties[8],
  );
}

/// [UserPreference] entity fields to define ObjectBox queries.
class UserPreference_ {
  /// See [UserPreference.id].
  static final id = obx.QueryIntegerProperty<UserPreference>(
    _entities[4].properties[0],
  );

  /// See [UserPreference.key].
  static final key = obx.QueryStringProperty<UserPreference>(
    _entities[4].properties[1],
  );

  /// See [UserPreference.stringValue].
  static final stringValue = obx.QueryStringProperty<UserPreference>(
    _entities[4].properties[2],
  );

  /// See [UserPreference.intValue].
  static final intValue = obx.QueryIntegerProperty<UserPreference>(
    _entities[4].properties[3],
  );

  /// See [UserPreference.doubleValue].
  static final doubleValue = obx.QueryDoubleProperty<UserPreference>(
    _entities[4].properties[4],
  );

  /// See [UserPreference.boolValue].
  static final boolValue = obx.QueryBooleanProperty<UserPreference>(
    _entities[4].properties[5],
  );

  /// See [UserPreference.typeValue].
  static final typeValue = obx.QueryIntegerProperty<UserPreference>(
    _entities[4].properties[6],
  );

  /// See [UserPreference.timestamp].
  static final timestamp = obx.QueryIntegerProperty<UserPreference>(
    _entities[4].properties[7],
  );
}

/// [AlbumConfig] entity fields to define ObjectBox queries.
class AlbumConfig_ {
  /// See [AlbumConfig.id].
  static final id = obx.QueryIntegerProperty<AlbumConfig>(
    _entities[5].properties[0],
  );

  /// See [AlbumConfig.albumId].
  static final albumId = obx.QueryIntegerProperty<AlbumConfig>(
    _entities[5].properties[1],
  );

  /// See [AlbumConfig.includeSubdirectories].
  static final includeSubdirectories = obx.QueryBooleanProperty<AlbumConfig>(
    _entities[5].properties[2],
  );

  /// See [AlbumConfig.fileExtensions].
  static final fileExtensions = obx.QueryStringProperty<AlbumConfig>(
    _entities[5].properties[3],
  );

  /// See [AlbumConfig.autoRefresh].
  static final autoRefresh = obx.QueryBooleanProperty<AlbumConfig>(
    _entities[5].properties[4],
  );

  /// See [AlbumConfig.maxFileCount].
  static final maxFileCount = obx.QueryIntegerProperty<AlbumConfig>(
    _entities[5].properties[5],
  );

  /// See [AlbumConfig.sortBy].
  static final sortBy = obx.QueryStringProperty<AlbumConfig>(
    _entities[5].properties[6],
  );

  /// See [AlbumConfig.sortAscending].
  static final sortAscending = obx.QueryBooleanProperty<AlbumConfig>(
    _entities[5].properties[7],
  );

  /// See [AlbumConfig.excludePatterns].
  static final excludePatterns = obx.QueryStringProperty<AlbumConfig>(
    _entities[5].properties[8],
  );

  /// See [AlbumConfig.enableAutoRules].
  static final enableAutoRules = obx.QueryBooleanProperty<AlbumConfig>(
    _entities[5].properties[9],
  );

  /// See [AlbumConfig.directories].
  static final directories = obx.QueryStringProperty<AlbumConfig>(
    _entities[5].properties[10],
  );

  /// See [AlbumConfig.lastScanTime].
  static final lastScanTime = obx.QueryDateProperty<AlbumConfig>(
    _entities[5].properties[11],
  );

  /// See [AlbumConfig.fileCount].
  static final fileCount = obx.QueryIntegerProperty<AlbumConfig>(
    _entities[5].properties[12],
  );

  /// See [AlbumConfig.fileExtensionsList].
  static final fileExtensionsList = obx.QueryStringVectorProperty<AlbumConfig>(
    _entities[5].properties[13],
  );

  /// See [AlbumConfig.excludePatternsList].
  static final excludePatternsList = obx.QueryStringVectorProperty<AlbumConfig>(
    _entities[5].properties[14],
  );

  /// See [AlbumConfig.directoriesList].
  static final directoriesList = obx.QueryStringVectorProperty<AlbumConfig>(
    _entities[5].properties[15],
  );
}

/// [VideoLibrary] entity fields to define ObjectBox queries.
class VideoLibrary_ {
  /// See [VideoLibrary.id].
  static final id = obx.QueryIntegerProperty<VideoLibrary>(
    _entities[6].properties[0],
  );

  /// See [VideoLibrary.name].
  static final name = obx.QueryStringProperty<VideoLibrary>(
    _entities[6].properties[1],
  );

  /// See [VideoLibrary.description].
  static final description = obx.QueryStringProperty<VideoLibrary>(
    _entities[6].properties[2],
  );

  /// See [VideoLibrary.coverImagePath].
  static final coverImagePath = obx.QueryStringProperty<VideoLibrary>(
    _entities[6].properties[3],
  );

  /// See [VideoLibrary.createdAt].
  static final createdAt = obx.QueryDateProperty<VideoLibrary>(
    _entities[6].properties[4],
  );

  /// See [VideoLibrary.modifiedAt].
  static final modifiedAt = obx.QueryDateProperty<VideoLibrary>(
    _entities[6].properties[5],
  );

  /// See [VideoLibrary.colorTheme].
  static final colorTheme = obx.QueryStringProperty<VideoLibrary>(
    _entities[6].properties[6],
  );

  /// See [VideoLibrary.isSystemLibrary].
  static final isSystemLibrary = obx.QueryBooleanProperty<VideoLibrary>(
    _entities[6].properties[7],
  );
}

/// [VideoLibraryConfig] entity fields to define ObjectBox queries.
class VideoLibraryConfig_ {
  /// See [VideoLibraryConfig.id].
  static final id = obx.QueryIntegerProperty<VideoLibraryConfig>(
    _entities[7].properties[0],
  );

  /// See [VideoLibraryConfig.videoLibraryId].
  static final videoLibraryId = obx.QueryIntegerProperty<VideoLibraryConfig>(
    _entities[7].properties[1],
  );

  /// See [VideoLibraryConfig.includeSubdirectories].
  static final includeSubdirectories =
      obx.QueryBooleanProperty<VideoLibraryConfig>(_entities[7].properties[2]);

  /// See [VideoLibraryConfig.fileExtensions].
  static final fileExtensions = obx.QueryStringProperty<VideoLibraryConfig>(
    _entities[7].properties[3],
  );

  /// See [VideoLibraryConfig.autoRefresh].
  static final autoRefresh = obx.QueryBooleanProperty<VideoLibraryConfig>(
    _entities[7].properties[4],
  );

  /// See [VideoLibraryConfig.maxFileCount].
  static final maxFileCount = obx.QueryIntegerProperty<VideoLibraryConfig>(
    _entities[7].properties[5],
  );

  /// See [VideoLibraryConfig.sortBy].
  static final sortBy = obx.QueryStringProperty<VideoLibraryConfig>(
    _entities[7].properties[6],
  );

  /// See [VideoLibraryConfig.sortAscending].
  static final sortAscending = obx.QueryBooleanProperty<VideoLibraryConfig>(
    _entities[7].properties[7],
  );

  /// See [VideoLibraryConfig.excludePatterns].
  static final excludePatterns = obx.QueryStringProperty<VideoLibraryConfig>(
    _entities[7].properties[8],
  );

  /// See [VideoLibraryConfig.enableAutoRules].
  static final enableAutoRules = obx.QueryBooleanProperty<VideoLibraryConfig>(
    _entities[7].properties[9],
  );

  /// See [VideoLibraryConfig.directories].
  static final directories = obx.QueryStringProperty<VideoLibraryConfig>(
    _entities[7].properties[10],
  );

  /// See [VideoLibraryConfig.lastScanTime].
  static final lastScanTime = obx.QueryDateProperty<VideoLibraryConfig>(
    _entities[7].properties[11],
  );

  /// See [VideoLibraryConfig.fileCount].
  static final fileCount = obx.QueryIntegerProperty<VideoLibraryConfig>(
    _entities[7].properties[12],
  );

  /// See [VideoLibraryConfig.fileExtensionsList].
  static final fileExtensionsList =
      obx.QueryStringVectorProperty<VideoLibraryConfig>(
        _entities[7].properties[13],
      );

  /// See [VideoLibraryConfig.excludePatternsList].
  static final excludePatternsList =
      obx.QueryStringVectorProperty<VideoLibraryConfig>(
        _entities[7].properties[14],
      );

  /// See [VideoLibraryConfig.directoriesList].
  static final directoriesList =
      obx.QueryStringVectorProperty<VideoLibraryConfig>(
        _entities[7].properties[15],
      );
}

/// [VideoLibraryFile] entity fields to define ObjectBox queries.
class VideoLibraryFile_ {
  /// See [VideoLibraryFile.id].
  static final id = obx.QueryIntegerProperty<VideoLibraryFile>(
    _entities[8].properties[0],
  );

  /// See [VideoLibraryFile.videoLibraryId].
  static final videoLibraryId = obx.QueryIntegerProperty<VideoLibraryFile>(
    _entities[8].properties[1],
  );

  /// See [VideoLibraryFile.filePath].
  static final filePath = obx.QueryStringProperty<VideoLibraryFile>(
    _entities[8].properties[2],
  );

  /// See [VideoLibraryFile.addedAt].
  static final addedAt = obx.QueryDateProperty<VideoLibraryFile>(
    _entities[8].properties[3],
  );

  /// See [VideoLibraryFile.caption].
  static final caption = obx.QueryStringProperty<VideoLibraryFile>(
    _entities[8].properties[4],
  );

  /// See [VideoLibraryFile.orderIndex].
  static final orderIndex = obx.QueryIntegerProperty<VideoLibraryFile>(
    _entities[8].properties[5],
  );
}
